experimentName: dcaseNAS
searchSpaceFile: search_space.json
trialCommand: python3 ../train_sed_nni.py -c default_SV.yaml
trialCodeDirectory: .
trialGpuNumber: 1
trialConcurrency: 1
maxExperimentDuration: 24h
maxTrialNumber: 1000
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local
  useActiveGpu: True