experimentName: dcaseNAS
searchSpaceFile: search_space.json
trialCommand: python3 train_sed.py --conf_file confs/default_SV.yaml --gpus 1 --fast_dev_run
trialCodeDirectory: ../
trialGpuNumber: 1
trialConcurrency: 1
maxExperimentDuration: 24h
maxTrialNumber: 1000
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local
  useActiveGpu: True