experimentName: dcaseNAS
searchSpaceFile: search_space.json
trialCommand: python3 encapsulate_run.py --command 'python3 train_sed.py --conf_file confs/config_nni.yaml --gpus 1'
trialCodeDirectory: ../
trialGpuNumber: 1
trialConcurrency: 1
maxExperimentDuration: 24h
maxTrialNumber: 1000
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: True